language: bash
services: docker

env:
- BACK_URL="http://les.viter.dk:3030"

script:
- docker build -t lesfrontstaging:latest .
- docker run -e BACK_URL=$BACK_URL --name tester lesfrontstaging:latest npm test
