language: bash
services: docker

env:
- BACK_URL="http://les.viter.dk:3000" FRONT_URL="http://runner:3000"

script:
- docker build -t lesfrontstaging:latest .
- docker network create mynet
- docker run --network mynet --name runner -d -p 3000:3000 lesfrontstaging:latest npm start 
- docker run --network mynet -e BACK_URL=$BACK_URL -e FRONT_URL=$FRONT_URL --name tester lesfrontstaging:latest npm test
